name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t simonsulymasec/nest-app
      - run: echo "pJA7Wt6W^i$$5-n" | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin
      - run: docker push simonsulymasec/nest-app
